version: '3.9'
services:
   django:
       build: .
       container_name: djangoJoo
       volumes:
         - .:/helloworld/Joo
       ports:
           - 5001:8000
       depends_on:
         - pgdb

   pgdb:
     image: postgres
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     container_name: pgdb2
     volumes:
       - postgredata:/var/lib/postgresql/data/

volumes:
  postgredata: null