# Generated by Django 4.1.6 on 2023-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labka2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(max_length=255),
        ),
    ]
