# Generated by Django 4.1.6 on 2023-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labka2', '0003_alter_book_number_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
